name: setup-rustup
description: setup rustup
inputs:
  rust-version:
    description: 'a version of rust for install'
    required: false
    default: stable
runs:
  using: composite
  steps:
    - id: setup-rustup
      name: setup rustup
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf > rustup.sh
        chmod 755 rustup.sh
        ./rustup.sh -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        rm rustup.sh
      shell: bash
    - id: setup-rust-version
      name: setup rust version
      run: |
        rustup toolchain add ${{inputs.rust-version}}
        rustup default ${{inputs.rust-version}}
      shell: bash
